### ISSUE TITLE
加载配置文件失败

### ISSUE THREAD

**Issue by angushushu** [CatMoe/AkaneField#36]
**描述：**
运行时后台报错，加载配置文件失败导致插件未能启动（奇怪的是回退到hotfix2版本后从正常域名进入也会被HostSpoof拦截）

**后台报错：**
'''
[04:52:00] [main/ERROR]: null加载配置文件时发生了错误..
[04:52:00] [main/WARN]: Exception encountered when loading plugin: AkaneField
java.lang.RuntimeException: Cannot load configuration files.
	at catmoe.fallencrystal.akanefield.AkaneFieldProxy.onEnable(AkaneFieldProxy.java:98) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-515.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:8a03f3d:515]
'''

**Comment by FallenCrystal** [comment]
发送配置文件.

**Comment by FallenCrystal** [comment]
看来你确实需要更新你的配置文件.  

```
checks:
  # 防止域欺骗
  hostspoof:
    # 是否开启
    # 调试功能
    enabled: true
    # 调试 将消息打印到控制台
    debug: false
    # 是否踢出
    # 请验证确认功能配置完毕且没问题之后再开启!
    kick: true
    # 允许的域或IP
    # 使用 [dot] 代替点 (.)
    allow-host:
      - "127[dot]0[dot]0[dot]1"
      - "global[dot]cubexmc[dot]org"
      - "play[dot]cubexmc[dot]org"
      - "play[dot]cubexmc[dot]cn"
```

  

```
checks:
  # 防止域欺骗
  hostspoof:
    # 是否开启
    # 调试功能
    enabled: true
    # 调试 将消息打印到控制台
    # 警告! 仅限调试使用 当功能正常运行时 请不要使用该功能.
    # 遭受攻击时打印垃圾邮件会消耗非常多的CPU!
    debug: false
    # 是否踢出
    # 请验证确认功能配置完毕且没问题之后再开启!
    kick: false
    # 在服务器收到攻击时自动切换策略
    # 在下面设置允许的域
    # 如果为false 则fallback到default策略.
    # 最有效的防御方法: 在下面的策略中添加gov.cn(?)
    switch-rules-on-attack: false
    # 允许的域或IP
    # 使用 [dot] 代替点 (.)
    allow-host:
      # 默认
      default:
        - "127[dot]0[dot]0[dot]1"
        - "mc[dot]miaomoe[dot]net"
      # 切换策略 需要确保switch-rules-on-attack为true
      # 不同的攻击模式选用不同的域
      # fallback策略只要激活了防御模式 都是通用的.
      # motd戒备模式不会影响玩家加入 没有意义.
      on-attack:
        # 空为不需要 会覆盖下面的rule
        # 请注意 即使您配置了fallback 踢出消息也会
        # 根据戒备模式而变化.
        fallback:
          - "mc[dot]miaomoe[dot]net"
        firewall:
          - "mc[dot]saksea[dot]net"
        block:
          - ""
        verify:
          - ""
```

**Comment by angushushu** [comment]
我明天试一下，把就配置删了好像不能自动生成新的

**Comment by FallenCrystal** [comment]
我懒得写 而且我不想将这些东西全部夹进jar里  
之后可能会考虑自动从github抓取文件并比较差异.  

`README.md`

```
自行编译
从储存库里复制config文件夹.
将构建成功的软件包和 config 文件夹拖入 BungeeCord\plugins\ 里
将 config 文件夹重命名为 AkaneField
根据情况调整配置
启动服务器
```

**Comment by FallenCrystal** [comment]
注意 当插件故障未能启动时 你需要重新启动BungeeCord
